DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS BOOK_AUTHOR;
DROP TABLE IF EXISTS BOOK_GENRE;

CREATE TABLE BOOK(
  ID UUID DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE AUTHOR(
  ID UUID DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY,
  FULL_NAME VARCHAR(255)
);

CREATE TABLE BOOK_AUTHOR(
  ID_BOOK UUID,
  ID_AUTHOR UUID,
  foreign key (ID_BOOK) references BOOK(ID),
  foreign key (ID_AUTHOR) references AUTHOR(ID)
);


CREATE TABLE GENRE(
  ID UUID DEFAULT RANDOM_UUID() NOT NULL PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE BOOK_GENRE(
  ID_BOOK UUID,
  ID_GENRE UUID,
  foreign key (ID_BOOK) references BOOK(ID),
  foreign key (ID_GENRE) references GENRE(ID)
);